---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "postgres-hangfire-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "postgres-hangfire"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgres_hangfire.postgres_hangfire_password }}"
type: "Opaque"
