---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "portal-bff-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "portal-bff"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  Bff__Keycloak__ClientSecret: "{{ .Values.secrets.portal_bff.portal_bff_client_secret }}"
  ConnectionStrings__rabbitmq: "amqp://guest:{{ .Values.secrets.portal_bff.rabbitmq_password }}@rabbitmq-service:5672"
  RABBITMQ_PASSWORD: "{{ .Values.secrets.portal_bff.rabbitmq_password }}"
  RABBITMQ_URI: "amqp://guest:{{ .Values.secrets.portal_bff.rabbitmq_password }}@rabbitmq-service:5672"
  ConnectionStrings__valkey: "valkey-service:6379,password={{ .Values.secrets.portal_bff.valkey_password }}"
  VALKEY_PASSWORD: "{{ .Values.secrets.portal_bff.valkey_password }}"
  VALKEY_URI: "valkey://:{{ .Values.secrets.portal_bff.valkey_password }}@valkey-service:6379"
  ConnectionStrings__Hangfire: "Host=postgres-hangfire-service;Port=5432;Username=postgres;Password={{ .Values.secrets.portal_bff.postgres_hangfire_password }};Database=dialysis_hangfire"
  HANGFIRE_PASSWORD: "{{ .Values.secrets.portal_bff.postgres_hangfire_password }}"
  HANGFIRE_URI: "postgresql://postgres:{{ .Values.secrets.portal_bff.postgres_hangfire_password }}@postgres-hangfire-service:5432/dialysis_hangfire"
  Bff__Events__RabbitMq__ConnectionUri: "amqp://guest:{{ .Values.secrets.portal_bff.rabbitmq_password }}@rabbitmq-service:5672"
  Bff__Events__SignalR__BackplaneConnectionString: "valkey-service:6379,password={{ .Values.secrets.portal_bff.valkey_password }}"
type: "Opaque"
