---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "lab-api-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "lab-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.lab_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.lab_api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.lab_api.port_http | int | toString }}"
  LAB_HOST: "{{ .Values.config.lab_api.LAB_HOST }}"
  LAB_PORT: "{{ .Values.config.lab_api.LAB_PORT }}"
  LAB_USERNAME: "{{ .Values.config.lab_api.LAB_USERNAME }}"
  LAB_JDBCCONNECTIONSTRING: "{{ .Values.config.lab_api.LAB_JDBCCONNECTIONSTRING }}"
  LAB_DATABASENAME: "{{ .Values.config.lab_api.LAB_DATABASENAME }}"
  HANGFIRE_HOST: "{{ .Values.config.lab_api.HANGFIRE_HOST }}"
  HANGFIRE_PORT: "{{ .Values.config.lab_api.HANGFIRE_PORT }}"
  HANGFIRE_USERNAME: "{{ .Values.config.lab_api.HANGFIRE_USERNAME }}"
  HANGFIRE_JDBCCONNECTIONSTRING: "{{ .Values.config.lab_api.HANGFIRE_JDBCCONNECTIONSTRING }}"
  HANGFIRE_DATABASENAME: "{{ .Values.config.lab_api.HANGFIRE_DATABASENAME }}"
  RABBITMQ_HOST: "{{ .Values.config.lab_api.RABBITMQ_HOST }}"
  RABBITMQ_PORT: "{{ .Values.config.lab_api.RABBITMQ_PORT }}"
  RABBITMQ_USERNAME: "{{ .Values.config.lab_api.RABBITMQ_USERNAME }}"
  VALKEY_HOST: "{{ .Values.config.lab_api.VALKEY_HOST }}"
  VALKEY_PORT: "{{ .Values.config.lab_api.VALKEY_PORT }}"
  Lab__Transponder__EnableOutboxRelay: "{{ .Values.config.lab_api.Lab__Transponder__EnableOutboxRelay }}"
  Lab__Authentication__Authority: "{{ .Values.config.lab_api.Lab__Authentication__Authority }}"
  Lab__Authentication__Audience: "{{ .Values.config.lab_api.Lab__Authentication__Audience }}"
