---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "ehr-api-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "ehr-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.ehr_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.ehr_api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.ehr_api.port_http | int | toString }}"
  EHR_HOST: "{{ .Values.config.ehr_api.EHR_HOST }}"
  EHR_PORT: "{{ .Values.config.ehr_api.EHR_PORT }}"
  EHR_USERNAME: "{{ .Values.config.ehr_api.EHR_USERNAME }}"
  EHR_JDBCCONNECTIONSTRING: "{{ .Values.config.ehr_api.EHR_JDBCCONNECTIONSTRING }}"
  EHR_DATABASENAME: "{{ .Values.config.ehr_api.EHR_DATABASENAME }}"
  RABBITMQ_HOST: "{{ .Values.config.ehr_api.RABBITMQ_HOST }}"
  RABBITMQ_PORT: "{{ .Values.config.ehr_api.RABBITMQ_PORT }}"
  RABBITMQ_USERNAME: "{{ .Values.config.ehr_api.RABBITMQ_USERNAME }}"
  VALKEY_HOST: "{{ .Values.config.ehr_api.VALKEY_HOST }}"
  VALKEY_PORT: "{{ .Values.config.ehr_api.VALKEY_PORT }}"
  Ehr__Transponder__EnableOutboxRelay: "{{ .Values.config.ehr_api.Ehr__Transponder__EnableOutboxRelay }}"
  Ehr__Authentication__Authority: "{{ .Values.config.ehr_api.Ehr__Authentication__Authority }}"
  Ehr__Authentication__Audience: "{{ .Values.config.ehr_api.Ehr__Authentication__Audience }}"
  Ehr__Demo__Enabled: "{{ .Values.config.ehr_api.Ehr__Demo__Enabled }}"
  Ehr__Demo__RegistrationSimulator: "{{ .Values.config.ehr_api.Ehr__Demo__RegistrationSimulator }}"
