---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "smartconnect-bff-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "smartconnect-bff"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.smartconnect_bff.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.smartconnect_bff.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  ASPNETCORE_URLS: "{{ .Values.config.smartconnect_bff.ASPNETCORE_URLS }}"
  Bff__Keycloak__Authority: "{{ .Values.config.smartconnect_bff.keycloak_authority }}"
  Bff__Module__ModuleApiAddress: "http://smartconnect-api-service:{{ .Values.parameters.smartconnect_api.port_http }}"
  ConnectionStrings__rabbitmq: "{{ .Values.config.smartconnect_bff.rabbitmq_connection }}"
  ConnectionStrings__valkey: "{{ .Values.config.smartconnect_bff.valkey_connection }}"
  Bff__Events__RabbitMq__ConnectionUri: "{{ .Values.config.smartconnect_bff.rabbitmq_connection }}"
  Bff__Events__SignalR__BackplaneConnectionString: "{{ .Values.config.smartconnect_bff.valkey_connection }}"
  HANGFIRE_HOST: "{{ .Values.config.smartconnect_bff.HANGFIRE_HOST }}"
  HANGFIRE_PORT: "{{ .Values.config.smartconnect_bff.HANGFIRE_PORT }}"
  HANGFIRE_USERNAME: "{{ .Values.config.smartconnect_bff.HANGFIRE_USERNAME }}"
  HANGFIRE_JDBCCONNECTIONSTRING: "{{ .Values.config.smartconnect_bff.HANGFIRE_JDBCCONNECTIONSTRING }}"
  HANGFIRE_DATABASENAME: "{{ .Values.config.smartconnect_bff.HANGFIRE_DATABASENAME }}"
