---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "postgres-sonarqube-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "postgres-sonarqube"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgres_sonarqube.sonar_pg_password }}"
type: "Opaque"
