---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "portal-bff-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "portal-bff"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  Bff__Keycloak__ClientSecret: "{{ .Values.secrets.portal_bff.portal_bff_client_secret }}"
type: "Opaque"
