---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "hie-bff-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "hie-bff"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.hie_bff.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.hie_bff.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  ASPNETCORE_URLS: "{{ .Values.config.hie_bff.ASPNETCORE_URLS }}"
  Bff__Keycloak__Authority: "{{ .Values.config.hie_bff.Bff__Keycloak__Authority }}"
  Bff__Module__ModuleApiAddress: "http://hie-api-service:{{ .Values.parameters.hie_api.port_http }}"
  RABBITMQ_HOST: "{{ .Values.config.hie_bff.RABBITMQ_HOST }}"
  RABBITMQ_PORT: "{{ .Values.config.hie_bff.RABBITMQ_PORT }}"
  RABBITMQ_USERNAME: "{{ .Values.config.hie_bff.RABBITMQ_USERNAME }}"
  VALKEY_HOST: "{{ .Values.config.hie_bff.VALKEY_HOST }}"
  VALKEY_PORT: "{{ .Values.config.hie_bff.VALKEY_PORT }}"
  Bff__Module__Aggregations__0__Address: "http://smartconnect-api-service:{{ .Values.parameters.smartconnect_api.port_http }}"
