---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "sonarqube-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "sonarqube"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  SONAR_JDBC_PASSWORD: "{{ .Values.secrets.sonarqube.sonar_pg_password }}"
type: "Opaque"
