---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "pdms-api-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "pdms-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.pdms_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.pdms_api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.pdms_api.port_http | int | toString }}"
  PDMS_HOST: "{{ .Values.config.pdms_api.PDMS_HOST }}"
  PDMS_PORT: "{{ .Values.config.pdms_api.PDMS_PORT }}"
  PDMS_USERNAME: "{{ .Values.config.pdms_api.PDMS_USERNAME }}"
  PDMS_JDBCCONNECTIONSTRING: "{{ .Values.config.pdms_api.PDMS_JDBCCONNECTIONSTRING }}"
  PDMS_DATABASENAME: "{{ .Values.config.pdms_api.PDMS_DATABASENAME }}"
  HANGFIRE_HOST: "{{ .Values.config.pdms_api.HANGFIRE_HOST }}"
  HANGFIRE_PORT: "{{ .Values.config.pdms_api.HANGFIRE_PORT }}"
  HANGFIRE_USERNAME: "{{ .Values.config.pdms_api.HANGFIRE_USERNAME }}"
  HANGFIRE_JDBCCONNECTIONSTRING: "{{ .Values.config.pdms_api.HANGFIRE_JDBCCONNECTIONSTRING }}"
  HANGFIRE_DATABASENAME: "{{ .Values.config.pdms_api.HANGFIRE_DATABASENAME }}"
  ConnectionStrings__rabbitmq: "{{ .Values.config.pdms_api.rabbitmq_connection }}"
  ConnectionStrings__valkey: "{{ .Values.config.pdms_api.valkey_connection }}"
  Pdms__Transponder__EnableOutboxRelay: "{{ .Values.config.pdms_api.Pdms__Transponder__EnableOutboxRelay }}"
  Pdms__Transponder__RabbitMq__ConnectionUri: "{{ .Values.config.pdms_api.rabbitmq_connection }}"
  Pdms__DistributedCache__Valkey__ConnectionString: "{{ .Values.config.pdms_api.valkey_connection }}"
  Pdms__Authentication__Authority: "{{ .Values.config.pdms_api.keycloak_authority }}"
  Pdms__Authentication__Audience: "{{ .Values.config.pdms_api.Pdms__Authentication__Audience }}"
