---
apiVersion: "policy/v1"
kind: "PodDisruptionBudget"
metadata:
  name: "pdms-api-pdb"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "pdms-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: "pdms-api"
