using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace Dialysis.DataSimulator;

/// <summary>
/// Renders a minimal one-page visit-summary PDF. The simulator uploads this (instead of plain text)
/// so the HIE Documents preview pipeline has a real <c>application/pdf</c> to route through pdfjs —
/// and so the signing / AcroForm-fill features have something to act on.
/// </summary>
internal static class VisitSummaryPdf
{
    // QuestPDF requires a license to be declared once before first use; Community is free for our use.
    // Mirrors src/backend/BuildingBlocks/Documents/.../QuestPdfDocumentRenderer.cs.
    static VisitSummaryPdf() => QuestPDF.Settings.License = LicenseType.Community;

    /// <summary>Renders <paramref name="body"/> under <paramref name="title"/> as PDF bytes.</summary>
    public static byte[] Render(string title, string body) =>
        Document.Create(container =>
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(2, Unit.Centimetre);
                page.Header().Text(title).SemiBold().FontSize(18);
                page.Content().PaddingVertical(12).Text(body).FontSize(12);
                page.Footer().AlignRight().Text("Generated by DataSimulator");
            }))
        .GeneratePdf();
}
