---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "lab-api-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "lab-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__Lab: "Host=postgres-lab-service;Port=5432;Username=postgres;Password={{ .Values.secrets.lab_api.postgres_lab_password }};Database=dialysis_lab"
  LAB_PASSWORD: "{{ .Values.secrets.lab_api.postgres_lab_password }}"
  LAB_URI: "postgresql://postgres:{{ .Values.secrets.lab_api.postgres_lab_password }}@postgres-lab-service:5432/dialysis_lab"
  ConnectionStrings__Hangfire: "Host=postgres-lab-service;Port=5432;Username=postgres;Password={{ .Values.secrets.lab_api.postgres_lab_password }};Database=dialysis_lab"
  HANGFIRE_PASSWORD: "{{ .Values.secrets.lab_api.postgres_lab_password }}"
  HANGFIRE_URI: "postgresql://postgres:{{ .Values.secrets.lab_api.postgres_lab_password }}@postgres-lab-service:5432/dialysis_lab"
type: "Opaque"
