---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "pdms-api-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "pdms-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__Pdms: "Host=postgres-pdms-service;Port=5432;Username=postgres;Password={{ .Values.secrets.pdms_api.postgres_pdms_password }};Database=dialysis_pdms"
  PDMS_PASSWORD: "{{ .Values.secrets.pdms_api.postgres_pdms_password }}"
  PDMS_URI: "postgresql://postgres:{{ .Values.secrets.pdms_api.postgres_pdms_password }}@postgres-pdms-service:5432/dialysis_pdms"
  ConnectionStrings__Hangfire: "Host=postgres-hangfire-service;Port=5432;Username=postgres;Password={{ .Values.secrets.pdms_api.postgres_hangfire_password }};Database=dialysis_hangfire"
  HANGFIRE_PASSWORD: "{{ .Values.secrets.pdms_api.postgres_hangfire_password }}"
  HANGFIRE_URI: "postgresql://postgres:{{ .Values.secrets.pdms_api.postgres_hangfire_password }}@postgres-hangfire-service:5432/dialysis_hangfire"
  ConnectionStrings__rabbitmq: "amqp://guest:{{ .Values.secrets.pdms_api.rabbitmq_password }}@rabbitmq-service:5672"
  RABBITMQ_PASSWORD: "{{ .Values.secrets.pdms_api.rabbitmq_password }}"
  RABBITMQ_URI: "amqp://guest:{{ .Values.secrets.pdms_api.rabbitmq_password }}@rabbitmq-service:5672"
  ConnectionStrings__valkey: "valkey-service:6379,password={{ .Values.secrets.pdms_api.valkey_password }}"
  VALKEY_PASSWORD: "{{ .Values.secrets.pdms_api.valkey_password }}"
  VALKEY_URI: "valkey://:{{ .Values.secrets.pdms_api.valkey_password }}@valkey-service:6379"
  Pdms__Transponder__RabbitMq__ConnectionUri: "amqp://guest:{{ .Values.secrets.pdms_api.rabbitmq_password }}@rabbitmq-service:5672"
  Pdms__DistributedCache__Valkey__ConnectionString: "valkey-service:6379,password={{ .Values.secrets.pdms_api.valkey_password }}"
type: "Opaque"
