---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "postgres-pdms-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "postgres-pdms"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgres_pdms.postgres_pdms_password }}"
type: "Opaque"
