---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "identity-bff-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "identity-bff"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__Hangfire: "Host=postgres-his-service;Port=5432;Username=postgres;Password={{ .Values.secrets.identity_bff.postgres_his_password }};Database=dialysis_his"
  HANGFIRE_PASSWORD: "{{ .Values.secrets.identity_bff.postgres_his_password }}"
  HANGFIRE_URI: "postgresql://postgres:{{ .Values.secrets.identity_bff.postgres_his_password }}@postgres-his-service:5432/dialysis_his"
  Identity__Keycloak__ClientSecret: "{{ .Values.secrets.identity_bff.identity_bff_client_secret }}"
type: "Opaque"
