---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "ehr-api-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "ehr-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__Ehr: "Host=postgres-ehr-service;Port=5432;Username=postgres;Password={{ .Values.secrets.ehr_api.postgres_ehr_password }};Database=dialysis_ehr"
  EHR_PASSWORD: "{{ .Values.secrets.ehr_api.postgres_ehr_password }}"
  EHR_URI: "postgresql://postgres:{{ .Values.secrets.ehr_api.postgres_ehr_password }}@postgres-ehr-service:5432/dialysis_ehr"
  ConnectionStrings__Hangfire: "Host=postgres-hangfire-service;Port=5432;Username=postgres;Password={{ .Values.secrets.ehr_api.postgres_hangfire_password }};Database=dialysis_hangfire"
  HANGFIRE_PASSWORD: "{{ .Values.secrets.ehr_api.postgres_hangfire_password }}"
  HANGFIRE_URI: "postgresql://postgres:{{ .Values.secrets.ehr_api.postgres_hangfire_password }}@postgres-hangfire-service:5432/dialysis_hangfire"
  ConnectionStrings__rabbitmq: "amqp://guest:{{ .Values.secrets.ehr_api.rabbitmq_password }}@rabbitmq-service:5672"
  RABBITMQ_PASSWORD: "{{ .Values.secrets.ehr_api.rabbitmq_password }}"
  RABBITMQ_URI: "amqp://guest:{{ .Values.secrets.ehr_api.rabbitmq_password }}@rabbitmq-service:5672"
  ConnectionStrings__valkey: "valkey-service:6379,password={{ .Values.secrets.ehr_api.valkey_password }}"
  VALKEY_PASSWORD: "{{ .Values.secrets.ehr_api.valkey_password }}"
  VALKEY_URI: "valkey://:{{ .Values.secrets.ehr_api.valkey_password }}@valkey-service:6379"
  Ehr__Transponder__RabbitMq__ConnectionUri: "amqp://guest:{{ .Values.secrets.ehr_api.rabbitmq_password }}@rabbitmq-service:5672"
  Ehr__DistributedCache__Valkey__ConnectionString: "valkey-service:6379,password={{ .Values.secrets.ehr_api.valkey_password }}"
type: "Opaque"
