---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "his-api-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "his-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__His: "Host=postgres-his-service;Port=5432;Username=postgres;Password={{ .Values.secrets.his_api.postgres_his_password }};Database=dialysis_his"
  HIS_PASSWORD: "{{ .Values.secrets.his_api.postgres_his_password }}"
  HIS_URI: "postgresql://postgres:{{ .Values.secrets.his_api.postgres_his_password }}@postgres-his-service:5432/dialysis_his"
  ConnectionStrings__Hangfire: "Host=postgres-his-service;Port=5432;Username=postgres;Password={{ .Values.secrets.his_api.postgres_his_password }};Database=dialysis_his"
  HANGFIRE_PASSWORD: "{{ .Values.secrets.his_api.postgres_his_password }}"
  HANGFIRE_URI: "postgresql://postgres:{{ .Values.secrets.his_api.postgres_his_password }}@postgres-his-service:5432/dialysis_his"
  ConnectionStrings__rabbitmq: "amqp://guest:{{ .Values.secrets.his_api.rabbitmq_password }}@rabbitmq-service:5672"
  RABBITMQ_PASSWORD: "{{ .Values.secrets.his_api.rabbitmq_password }}"
  RABBITMQ_URI: "amqp://guest:{{ .Values.secrets.his_api.rabbitmq_password }}@rabbitmq-service:5672"
  ConnectionStrings__valkey: "valkey-service:6379,password={{ .Values.secrets.his_api.valkey_password }}"
  VALKEY_PASSWORD: "{{ .Values.secrets.his_api.valkey_password }}"
  VALKEY_URI: "valkey://:{{ .Values.secrets.his_api.valkey_password }}@valkey-service:6379"
  His__Transponder__RabbitMq__ConnectionUri: "amqp://guest:{{ .Values.secrets.his_api.rabbitmq_password }}@rabbitmq-service:5672"
  His__DistributedCache__Valkey__ConnectionString: "valkey-service:6379,password={{ .Values.secrets.his_api.valkey_password }}"
type: "Opaque"
