---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "ehr-api-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "ehr-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.ehr_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.ehr_api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.ehr_api.port_http | int | toString }}"
  EHR_HOST: "{{ .Values.config.ehr_api.EHR_HOST }}"
  EHR_PORT: "{{ .Values.config.ehr_api.EHR_PORT }}"
  EHR_USERNAME: "{{ .Values.config.ehr_api.EHR_USERNAME }}"
  EHR_JDBCCONNECTIONSTRING: "{{ .Values.config.ehr_api.EHR_JDBCCONNECTIONSTRING }}"
  EHR_DATABASENAME: "{{ .Values.config.ehr_api.EHR_DATABASENAME }}"
  HANGFIRE_HOST: "{{ .Values.config.ehr_api.HANGFIRE_HOST }}"
  HANGFIRE_PORT: "{{ .Values.config.ehr_api.HANGFIRE_PORT }}"
  HANGFIRE_USERNAME: "{{ .Values.config.ehr_api.HANGFIRE_USERNAME }}"
  HANGFIRE_JDBCCONNECTIONSTRING: "{{ .Values.config.ehr_api.HANGFIRE_JDBCCONNECTIONSTRING }}"
  HANGFIRE_DATABASENAME: "{{ .Values.config.ehr_api.HANGFIRE_DATABASENAME }}"
  ConnectionStrings__rabbitmq: "{{ .Values.config.ehr_api.rabbitmq_connection }}"
  ConnectionStrings__valkey: "{{ .Values.config.ehr_api.valkey_connection }}"
  Ehr__Transponder__EnableOutboxRelay: "{{ .Values.config.ehr_api.Ehr__Transponder__EnableOutboxRelay }}"
  Ehr__Transponder__RabbitMq__ConnectionUri: "{{ .Values.config.ehr_api.rabbitmq_connection }}"
  Ehr__DistributedCache__Valkey__ConnectionString: "{{ .Values.config.ehr_api.valkey_connection }}"
  Ehr__Authentication__Authority: "{{ .Values.config.ehr_api.keycloak_authority }}"
  Ehr__Authentication__Audience: "{{ .Values.config.ehr_api.Ehr__Authentication__Audience }}"
