---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "ehr-api-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "ehr-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__Ehr: "Host=postgres-ehr-service;Port=5432;Username=postgres;Password={{ .Values.secrets.ehr_api.postgres_ehr_password }};Database=dialysis_ehr"
  EHR_PASSWORD: "{{ .Values.secrets.ehr_api.postgres_ehr_password }}"
  EHR_URI: "postgresql://postgres:{{ .Values.secrets.ehr_api.postgres_ehr_password }}@postgres-ehr-service:5432/dialysis_ehr"
  ConnectionStrings__Hangfire: "Host=postgres-ehr-service;Port=5432;Username=postgres;Password={{ .Values.secrets.ehr_api.postgres_ehr_password }};Database=dialysis_ehr"
  HANGFIRE_PASSWORD: "{{ .Values.secrets.ehr_api.postgres_ehr_password }}"
  HANGFIRE_URI: "postgresql://postgres:{{ .Values.secrets.ehr_api.postgres_ehr_password }}@postgres-ehr-service:5432/dialysis_ehr"
type: "Opaque"
