---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "smartconnect-api-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "smartconnect-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__SmartConnect: "Host=postgres-smartconnect-service;Port=5432;Username=postgres;Password={{ .Values.secrets.smartconnect_api.postgres_smartconnect_password }};Database=dialysis_smartconnect"
  SMARTCONNECT_PASSWORD: "{{ .Values.secrets.smartconnect_api.postgres_smartconnect_password }}"
  SMARTCONNECT_URI: "postgresql://postgres:{{ .Values.secrets.smartconnect_api.postgres_smartconnect_password }}@postgres-smartconnect-service:5432/dialysis_smartconnect"
  ConnectionStrings__Hangfire: "Host=postgres-smartconnect-service;Port=5432;Username=postgres;Password={{ .Values.secrets.smartconnect_api.postgres_smartconnect_password }};Database=dialysis_smartconnect"
  HANGFIRE_PASSWORD: "{{ .Values.secrets.smartconnect_api.postgres_smartconnect_password }}"
  HANGFIRE_URI: "postgresql://postgres:{{ .Values.secrets.smartconnect_api.postgres_smartconnect_password }}@postgres-smartconnect-service:5432/dialysis_smartconnect"
type: "Opaque"
