---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "pdms-bff-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "pdms-bff"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  Bff__Keycloak__ClientSecret: "{{ .Values.secrets.pdms_bff.pdms_bff_client_secret }}"
  ConnectionStrings__Hangfire: "Host=postgres-pdms-service;Port=5432;Username=postgres;Password={{ .Values.secrets.pdms_bff.postgres_pdms_password }};Database=dialysis_pdms"
  HANGFIRE_PASSWORD: "{{ .Values.secrets.pdms_bff.postgres_pdms_password }}"
  HANGFIRE_URI: "postgresql://postgres:{{ .Values.secrets.pdms_bff.postgres_pdms_password }}@postgres-pdms-service:5432/dialysis_pdms"
type: "Opaque"
