---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "smartconnect-web-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "smartconnect-web"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  NODE_ENV: "{{ .Values.config.smartconnect_web.NODE_ENV }}"
  BROWSER: "{{ .Values.config.smartconnect_web.BROWSER }}"
  VITE_GATEWAY_URL: "{{ .Values.config.smartconnect_web.VITE_GATEWAY_URL }}"
  VITE_API_BASE_URL: "{{ .Values.config.smartconnect_web.VITE_API_BASE_URL }}"
  PORT: "{{ .Values.config.smartconnect_web.PORT }}"
