---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "identity-bff-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "identity-bff"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.identity_bff.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.identity_bff.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.identity_bff.HTTP_PORTS }}"
  HANGFIRE_HOST: "{{ .Values.config.identity_bff.HANGFIRE_HOST }}"
  HANGFIRE_PORT: "{{ .Values.config.identity_bff.HANGFIRE_PORT }}"
  HANGFIRE_USERNAME: "{{ .Values.config.identity_bff.HANGFIRE_USERNAME }}"
  HANGFIRE_JDBCCONNECTIONSTRING: "{{ .Values.config.identity_bff.HANGFIRE_JDBCCONNECTIONSTRING }}"
  HANGFIRE_DATABASENAME: "{{ .Values.config.identity_bff.HANGFIRE_DATABASENAME }}"
  ASPNETCORE_URLS: "{{ .Values.config.identity_bff.ASPNETCORE_URLS }}"
  Identity__Keycloak__Authority: "{{ .Values.config.identity_bff.Identity__Keycloak__Authority }}"
  ReverseProxy__Clusters__his__Destinations__d1__Address: "http://his-api-service:{{ .Values.parameters.his_api.port_http }}"
