---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "admin-bff-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "admin-bff"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  Bff__Keycloak__ClientSecret: "{{ .Values.secrets.admin_bff.admin_bff_client_secret }}"
type: "Opaque"
