parameters:
  ehr_api:
    port_http: 8080
    ehr_api_image: "ehr-api:latest"
  ehr_bff:
    ehr_bff_image: "ehr-bff:latest"
  ehr_web:
    ehr_web_image: "ehr-web:latest"
secrets:
  postgres_ehr:
    postgres_ehr_password: ""
  ehr_api:
    ConnectionStrings__Ehr: ""
    postgres_ehr_password: ""
    EHR_URI: ""
    ConnectionStrings__Hangfire: ""
    HANGFIRE_URI: ""
  ehr_bff:
    ehr_bff_client_secret: ""
    ConnectionStrings__Hangfire: ""
    postgres_ehr_password: ""
    HANGFIRE_URI: ""
config:
  postgres_ehr:
    POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    POSTGRES_USER: "postgres"
  ehr_api:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: ""
    EHR_HOST: "postgres-ehr-service"
    EHR_PORT: "5432"
    EHR_USERNAME: "postgres"
    EHR_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-ehr-service:5432/dialysis_ehr"
    EHR_DATABASENAME: "dialysis_ehr"
    HANGFIRE_HOST: "postgres-ehr-service"
    HANGFIRE_PORT: "5432"
    HANGFIRE_USERNAME: "postgres"
    HANGFIRE_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-ehr-service:5432/dialysis_ehr"
    HANGFIRE_DATABASENAME: "dialysis_ehr"
    rabbitmq_connection: "amqp://guest:CHANGE-ME@rabbitmq-service:5672"
    valkey_connection: "valkey-service:6379,password=CHANGE-ME"
    Ehr__Transponder__EnableOutboxRelay: "true"
    keycloak_authority: "http://keycloak-service:8081/realms/dialysis"
    Ehr__Authentication__Audience: "account"
  ehr_bff:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ASPNETCORE_URLS: "http://+:5302"
    keycloak_authority: "http://keycloak-service:8081/realms/dialysis"
    Bff__Module__ModuleApiAddress: ""
    rabbitmq_connection: "amqp://guest:CHANGE-ME@rabbitmq-service:5672"
    valkey_connection: "valkey-service:6379,password=CHANGE-ME"
    HANGFIRE_HOST: "postgres-ehr-service"
    HANGFIRE_PORT: "5432"
    HANGFIRE_USERNAME: "postgres"
    HANGFIRE_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-ehr-service:5432/dialysis_ehr"
    HANGFIRE_DATABASENAME: "dialysis_ehr"
    Bff__Module__Aggregations__0__Address: "http://hie-api-service:8080"
    Bff__Module__Aggregations__1__Address: "http://lab-api-service:8080"
    Bff__Module__Aggregations__2__Address: "http://smartconnect-api-service:8080"
  ehr_web:
    NODE_ENV: "production"
    BROWSER: "none"
    VITE_GATEWAY_URL: "http://gateway-service:9090"
    VITE_API_BASE_URL: "http://gateway-service:9090"
    PORT: "5332"
