// <auto-generated />
using System;
using Dialysis.SmartConnect.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Postgresql.Migrations
{
    [DbContext(typeof(SmartConnectDbContext))]
    [Migration("20260513202641_AddAttachments")]
    partial class AddAttachments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributesJson")
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.HasIndex("Category", "Timestamp");

                    b.ToTable("AuditEvents", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.CodeTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JsDoc")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("CodeTemplates", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.CodeTemplateLibraryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoLinkNewFlows")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkedFlowIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CodeTemplateLibraries", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.FlowGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("FlowGroups", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.IntegrationFlowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PipelineJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RuntimeState")
                        .HasColumnType("integer");

                    b.Property<string>("TagsJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("IntegrationFlows", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.MessageLedgerEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IntegrationMessageId")
                        .HasColumnType("uuid");

                    b.Property<int?>("OutboundRouteOrdinal")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PayloadSnapshot")
                        .HasColumnType("bytea");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FlowId", "CreatedAtUtc");

                    b.ToTable("MessageLedgerEntries", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.VariableMapEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "FlowId", "Key")
                        .IsUnique();

                    b.ToTable("VariableMapEntries", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.CodeTemplateEntity", b =>
                {
                    b.HasOne("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.CodeTemplateLibraryEntity", null)
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
