// <auto-generated />

#nullable disable

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Postgresql.Migrations
{
    [DbContext(typeof(SmartConnectDbContext))]
    [Migration("20260526021412_AddEndpoints")]
    partial class AddEndpoints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.AlertEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionOutcomesJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ErrorDetail")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("ErrorType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RuleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.HasIndex("OccurredAtUtc");

                    b.HasIndex("RuleId");

                    b.ToTable("AlertEvents", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.AlertRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActionsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean");

                    b.Property<string>("EnabledFlowIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ErrorPatternsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<int>("ThrottleWindowSeconds")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Enabled");

                    b.ToTable("AlertRules", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.AttachmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("Data")
                        .HasColumnType("bytea");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("FlowId");

                    b.HasIndex("MessageId");

                    b.ToTable("Attachments", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AttributesJson")
                        .HasColumnType("text");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<Guid?>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("FlowId");

                    b.HasIndex("Category", "Timestamp");

                    b.ToTable("AuditEvents", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.CasBlobRefEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AttachmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("RefCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AttachmentId")
                        .IsUnique();

                    b.HasIndex("ContentHash");

                    b.ToTable("CasBlobRefs", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.CodeTemplateEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContextsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JsDoc")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("LibraryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Position")
                        .HasColumnType("integer");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("CodeTemplates", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.CodeTemplateLibraryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AutoLinkNewFlows")
                        .HasColumnType("boolean");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("LastModifiedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LinkedFlowIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Revision")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CodeTemplateLibraries", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.DicomInstanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("BlobId")
                        .HasColumnType("uuid");

                    b.Property<string>("Modality")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("PatientId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PatientName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("ReceivedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SeriesInstanceUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("SopClassUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("SopInstanceUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("StudyInstanceUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SopInstanceUid")
                        .IsUnique();

                    b.HasIndex("StudyInstanceUid");

                    b.HasIndex("PatientId", "ReceivedUtc");

                    b.ToTable("DicomInstances", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.EndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Endpoints", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.FlowGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("FlowGroups", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.IntegrationFlowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PipelineJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RuntimeState")
                        .HasColumnType("integer");

                    b.Property<string>("TagsJson")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("IntegrationFlows", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.MessageLedgerEntryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Detail")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IntegrationMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<int?>("OutboundRouteOrdinal")
                        .HasColumnType("integer");

                    b.Property<byte[]>("PayloadSnapshot")
                        .HasColumnType("bytea");

                    b.Property<string>("SenderId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MessageType");

                    b.HasIndex("SenderId");

                    b.HasIndex("FlowId", "CreatedAtUtc");

                    b.ToTable("MessageLedgerEntries", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.VariableMapEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<int>("Scope")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Scope", "FlowId", "Key")
                        .IsUnique();

                    b.ToTable("VariableMapEntries", "smartconnect");
                });

            modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.CodeTemplateEntity", b =>
                {
                    b.HasOne("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.CodeTemplateLibraryEntity", null)
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
