import {
  test,
  expect,
  mockAuth,
  stubRealtime,
  stubApiCatchAll,
  gotoWorkflow,
  installDocumentRoutes,
} from "./fixtures";

/**
 * AcroForm PDF workflow walkthrough (recorded to video): the operator opens the branded,
 * AcroForm-enabled dialysis invoice, pdfjs renders it inline and surfaces the editable fields,
 * the operator fills bill-to / payer / PO / remarks and ticks Reviewed, then Save bakes the
 * values into the document (POST …/fill). Backend is fully mocked; the served PDF is the real
 * branded fixture generated by BrandedPdfFixtureGenerator so the video shows the corporate template.
 */

const INVOICE_ID = "inv-2026-0042";

const invoiceRow = {
  id: INVOICE_ID,
  patientId: "22222222-2222-2222-2222-222222222222",
  kind: "invoice",
  title: "Invoice INV-2026-0042",
  mimeType: "application/pdf",
  languageCode: "en-US",
  status: "Current",
  source: "Billing",
  size: 43726,
  createdAtUtc: "2026-06-08T10:00:00Z",
  signatureCount: 0,
  hasAcroForms: true,
  hasJavascript: false,
  category: "11111111",
};

const invoiceDetail = (signed: boolean) => ({
  ...invoiceRow,
  createdBy: "demo-staff",
  contentHash: "f1d2c3b4a5e6f7081920",
  allowJavaScriptExecution: false,
  signatures: signed
    ? [
        {
          id: "sig-1",
          signerKind: "Platform",
          certThumbprint: "AB12CD34EF560718293A",
          signedAtUtc: "2026-06-08T10:05:00Z",
          padesLevel: "LT",
          signatureFormat: "Aes",
          revocationEvidenceFormat: "Both",
        },
      ]
    : [],
});

test.describe("hie-web — AcroForm invoice workflow", () => {
  test("generate → view → edit fields → fill", async ({ page }) => {
    await stubRealtime(page);
    await mockAuth(page, {
      permissions: ["hie.documents.list", "hie.documents.read", "hie.documents.fill"],
    });
    await stubApiCatchAll(page);
    await installDocumentRoutes(page, {
      id: INVOICE_ID,
      rows: [invoiceRow],
      detail: invoiceDetail,
      pdfFixture: "invoice-acroform.pdf",
    });

    await gotoWorkflow(page, "/hie/admin/documents", "Documents");

    // The branded invoice is indexed in the documents board; open it in the viewer drawer.
    await expect(page.getByText("Invoice INV-2026-0042")).toBeVisible();
    await page.getByRole("button", { name: "Open" }).first().click();

    const drawer = page.getByRole("dialog");
    await expect(drawer.getByRole("heading", { name: "Invoice INV-2026-0042" })).toBeVisible();

    // pdfjs parses the AcroForm and the drawer surfaces each editable field — wait for the first one
    // (the panel shows "Loading form fields…" until getFieldObjects resolves).
    const billTo = page.getByLabel("Bill to (name)");
    await expect(billTo).toBeVisible({ timeout: 20_000 });

    // The billing clerk completes the editable fields.
    await billTo.fill("Acme Dialysis Center");
    await page.getByLabel("Payer").selectOption("MEDICARE");
    await page.getByLabel("PO number").fill("PO-55821");
    await page.getByLabel("Remarks").fill("Reviewed against the June fee schedule.");
    await page.getByLabel("Reviewed").check();

    // Save bakes the values into the PDF (mocked /fill) and the panel confirms.
    await page.getByRole("button", { name: "Save changes" }).click();
    await expect(page.getByText(/Saved \d+ field\(s\) into the PDF\./)).toBeVisible();
  });
});
