import { join } from "node:path";
import {
  test,
  expect,
  mockAuth,
  stubRealtime,
  stubApiCatchAll,
  gotoWorkflow,
  installDocumentRoutes,
} from "./fixtures";
import { type Page } from "@playwright/test";

/**
 * AcroForm PDF workflow walkthrough (recorded to video + a labelled screenshot sequence): the
 * operator opens the branded, AcroForm-enabled dialysis invoice, pdfjs renders it inline and
 * surfaces the editable fields, the operator fills bill-to / payer / PO / remarks and ticks
 * Reviewed, then Save bakes the values into the document (POST …/fill). Backend is fully mocked;
 * the served PDF is the real branded fixture generated by BrandedPdfFixtureGenerator so the video
 * shows the corporate template.
 *
 * Each stage is a `test.step(...)` so the HTML report reads like a tutorial, and each stage drops a
 * numbered still into `e2e-artifacts/hie-web/tutorial/` (stable filenames → overwritten every run,
 * gitignored). See `e2e/acroform-tutorial.md` for the guide that consumes these artifacts.
 */

const INVOICE_ID = "inv-2026-0042";

/** Numbered tutorial stills land beside (not inside) the wiped `test-results/` output dir, so they
 *  survive the start-of-run clean and overwrite by filename — a stable set the guide can reference. */
const TUTORIAL_DIR = join(process.cwd(), "..", "..", "..", "e2e-artifacts", "hie-web", "tutorial");
const shot = (page: Page, name: string) => page.screenshot({ path: join(TUTORIAL_DIR, name) });

const invoiceRow = {
  id: INVOICE_ID,
  patientId: "22222222-2222-2222-2222-222222222222",
  kind: "invoice",
  title: "Invoice INV-2026-0042",
  mimeType: "application/pdf",
  languageCode: "en-US",
  status: "Current",
  source: "Billing",
  size: 43726,
  createdAtUtc: "2026-06-08T10:00:00Z",
  signatureCount: 0,
  hasAcroForms: true,
  hasJavascript: false,
  category: "11111111",
};

const invoiceDetail = (signed: boolean) => ({
  ...invoiceRow,
  createdBy: "demo-staff",
  contentHash: "f1d2c3b4a5e6f7081920",
  allowJavaScriptExecution: false,
  signatures: signed
    ? [
        {
          id: "sig-1",
          signerKind: "Platform",
          certThumbprint: "AB12CD34EF560718293A",
          signedAtUtc: "2026-06-08T10:05:00Z",
          padesLevel: "LT",
          signatureFormat: "Aes",
          revocationEvidenceFormat: "Both",
        },
      ]
    : [],
});

test.describe("hie-web — AcroForm invoice workflow", () => {
  test("generate → view → edit fields → fill", async ({ page }) => {
    await stubRealtime(page);
    await mockAuth(page, {
      permissions: ["hie.documents.list", "hie.documents.read", "hie.documents.fill"],
    });
    await stubApiCatchAll(page);
    await installDocumentRoutes(page, {
      id: INVOICE_ID,
      rows: [invoiceRow],
      detail: invoiceDetail,
      pdfFixture: "invoice-acroform.pdf",
    });

    await test.step("1. The documents board lists the branded AcroForm invoice", async () => {
      await gotoWorkflow(page, "/hie/admin/documents", "Documents");
      await expect(page.getByText("Invoice INV-2026-0042")).toBeVisible();
      await shot(page, "01-documents-board.png");
    });

    const drawer = page.getByRole("dialog");
    await test.step("2. Open the invoice — pdfjs renders the corporate template inline", async () => {
      await page.getByRole("button", { name: "Open" }).first().click();
      await expect(drawer.getByRole("heading", { name: "Invoice INV-2026-0042" })).toBeVisible();
      await shot(page, "02-invoice-opened.png");
    });

    // pdfjs parses the AcroForm and the drawer surfaces each editable field — wait for the first one
    // (the panel shows "Loading form fields…" until getFieldObjects resolves).
    const billTo = page.getByLabel("Bill to (name)");
    await test.step("3. The AcroForm fields are detected and become editable", async () => {
      await expect(billTo).toBeVisible({ timeout: 20_000 });
      await shot(page, "03-fields-detected.png");
    });

    await test.step("4. The billing clerk completes the editable fields", async () => {
      await billTo.fill("Acme Dialysis Center");
      await page.getByLabel("Payer").selectOption("MEDICARE");
      await page.getByLabel("PO number").fill("PO-55821");
      await page.getByLabel("Remarks").fill("Reviewed against the June fee schedule.");
      await page.getByLabel("Reviewed").check();
      await shot(page, "04-fields-completed.png");
    });

    await test.step("5. Save bakes the values into the PDF (POST …/fill)", async () => {
      await page.getByRole("button", { name: "Save changes" }).click();
      await expect(page.getByText(/Saved \d+ field\(s\) into the PDF\./)).toBeVisible();
      await shot(page, "05-saved.png");
    });
  });
});
