---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "gateway-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "gateway"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.gateway.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.gateway.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.gateway.HTTP_PORTS }}"
  ASPNETCORE_URLS: "{{ .Values.config.gateway.ASPNETCORE_URLS }}"
  HIS_API_HTTP: "http://his-api-service:{{ .Values.parameters.his_api.port_http }}"
  services__his-api__http__0: "http://his-api-service:{{ .Values.parameters.his_api.port_http }}"
  HIS_API_HTTPS: "https://his-api-service:{{ .Values.parameters.his_api.port_http }}"
  EHR_API_HTTP: "http://ehr-api-service:{{ .Values.parameters.ehr_api.port_http }}"
  services__ehr-api__http__0: "http://ehr-api-service:{{ .Values.parameters.ehr_api.port_http }}"
  EHR_API_HTTPS: "https://ehr-api-service:{{ .Values.parameters.ehr_api.port_http }}"
  PDMS_API_HTTP: "http://pdms-api-service:{{ .Values.parameters.pdms_api.port_http }}"
  services__pdms-api__http__0: "http://pdms-api-service:{{ .Values.parameters.pdms_api.port_http }}"
  PDMS_API_HTTPS: "https://pdms-api-service:{{ .Values.parameters.pdms_api.port_http }}"
  SMARTCONNECT_API_HTTP: "http://smartconnect-api-service:{{ .Values.parameters.smartconnect_api.port_http }}"
  services__smartconnect-api__http__0: "http://smartconnect-api-service:{{ .Values.parameters.smartconnect_api.port_http }}"
  SMARTCONNECT_API_HTTPS: "https://smartconnect-api-service:{{ .Values.parameters.smartconnect_api.port_http }}"
  HIE_API_HTTP: "http://hie-api-service:{{ .Values.parameters.hie_api.port_http }}"
  services__hie-api__http__0: "http://hie-api-service:{{ .Values.parameters.hie_api.port_http }}"
  HIE_API_HTTPS: "https://hie-api-service:{{ .Values.parameters.hie_api.port_http }}"
  IDENTITY_BFF_HTTP: "{{ .Values.config.gateway.IDENTITY_BFF_HTTP }}"
  services__identity-bff__http__0: "{{ .Values.config.gateway.services__identity_bff__http__0 }}"
  IDENTITY_BFF_HTTPS: "{{ .Values.config.gateway.IDENTITY_BFF_HTTPS }}"
  Gateway__Authority: "{{ .Values.config.gateway.Gateway__Authority }}"
  Gateway__Audience: "{{ .Values.config.gateway.Gateway__Audience }}"
  Gateway__RequireAuthentication: "{{ .Values.config.gateway.Gateway__RequireAuthentication }}"
  ReverseProxy__Clusters__identity__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__identity__Destinations__d1__Address }}"
