---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "postgres-ehr-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "postgres-ehr"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgres_ehr.postgres_ehr_password }}"
type: "Opaque"
