parameters:
  identity_bff:
    identity_bff_image: "identity-bff:latest"
  admin_bff:
    admin_bff_image: "admin-bff:latest"
  identity_web:
    identity_web_image: "identity-web:latest"
secrets:
  identity_bff:
    identity_bff_client_secret: ""
  admin_bff:
    admin_bff_client_secret: ""
config:
  keycloak:
    KC_BOOTSTRAP_ADMIN_USERNAME: "admin"
    KC_BOOTSTRAP_ADMIN_PASSWORD: "admin"
    KC_DB: "dev-mem"
    KC_HEALTH_ENABLED: "true"
    KC_HTTP_ENABLED: "true"
  identity_bff:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: "5275"
    hangfire_his_connection: "Host=postgres-his-service;Port=5432;Username=postgres;Password=CHANGE-ME;Database=dialysis_his"
    ASPNETCORE_URLS: "http://+:5275"
    Identity__Keycloak__Authority: "http://keycloak-service:8080/realms/dialysis"
    ReverseProxy__Clusters__his__Destinations__d1__Address: "http://his-api-service:8080/"
  admin_bff:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    ASPNETCORE_URLS: "http://+:5306"
    Bff__Keycloak__Authority: "http://keycloak-service:8080/realms/dialysis"
    Bff__Module__ModuleApiAddress: "http://hie-api-service:8080"
    rabbitmq_connection: "amqp://guest:CHANGE-ME@rabbitmq-service:5672"
    valkey_connection: "valkey-service:6379,password=CHANGE-ME"
    hangfire_hie_connection: "Host=postgres-hie-service;Port=5432;Username=postgres;Password=CHANGE-ME;Database=dialysis_hie"
    Bff__Module__Aggregations__0__Address: "http://his-api-service:8080"
    Bff__Module__Aggregations__1__Address: "http://ehr-api-service:8080"
    Bff__Module__Aggregations__2__Address: "http://pdms-api-service:8080"
    Bff__Module__Aggregations__3__Address: "http://smartconnect-api-service:8080"
  identity_web:
    NODE_ENV: "production"
    BROWSER: "none"
    VITE_GATEWAY_URL: "http://gateway-service:9090"
    VITE_API_BASE_URL: "http://gateway-service:9090"
    PORT: "5336"
