---
apiVersion: "apps/v1"
kind: "StatefulSet"
metadata:
  name: "postgres-his-statefulset"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "postgres-his"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Chart.Name }}"
        app.kubernetes.io/component: "postgres-his"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - image: "docker.io/postgres:17-alpine"
          name: "postgres-his"
          envFrom:
            - configMapRef:
                name: "postgres-his-config"
            - secretRef:
                name: "postgres-his-secrets"
          ports:
            - name: "tcp"
              protocol: "TCP"
              containerPort: 5432
          resources:
            limits:
              cpu: "500m"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          volumeMounts:
            - name: "dialysis-postgres-his-data"
              mountPath: "/var/lib/postgresql/data"
          imagePullPolicy: "IfNotPresent"
      volumes:
        - name: "dialysis-postgres-his-data"
          emptyDir: {}
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Chart.Name }}"
      app.kubernetes.io/component: "postgres-his"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  replicas: 1
  persistentVolumeClaimRetentionPolicy: {}
  updateStrategy:
    rollingUpdate: {}
    type: "RollingUpdate"
