---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "hie-api-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "hie-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__Hie: "Host=postgres-hie-service;Port=5432;Username=postgres;Password={{ .Values.secrets.hie_api.postgres_hie_password }};Database=dialysis_hie"
  HIE_PASSWORD: "{{ .Values.secrets.hie_api.postgres_hie_password }}"
  HIE_URI: "postgresql://postgres:{{ .Values.secrets.hie_api.postgres_hie_password }}@postgres-hie-service:5432/dialysis_hie"
  ConnectionStrings__Hangfire: "Host=postgres-hie-service;Port=5432;Username=postgres;Password={{ .Values.secrets.hie_api.postgres_hie_password }};Database=dialysis_hie"
  HANGFIRE_PASSWORD: "{{ .Values.secrets.hie_api.postgres_hie_password }}"
  HANGFIRE_URI: "postgresql://postgres:{{ .Values.secrets.hie_api.postgres_hie_password }}@postgres-hie-service:5432/dialysis_hie"
  ConnectionStrings__rabbitmq: "amqp://guest:{{ .Values.secrets.hie_api.rabbitmq_password }}@rabbitmq-service:5672"
  RABBITMQ_PASSWORD: "{{ .Values.secrets.hie_api.rabbitmq_password }}"
  RABBITMQ_URI: "amqp://guest:{{ .Values.secrets.hie_api.rabbitmq_password }}@rabbitmq-service:5672"
  ConnectionStrings__valkey: "valkey-service:6379,password={{ .Values.secrets.hie_api.valkey_password }}"
  VALKEY_PASSWORD: "{{ .Values.secrets.hie_api.valkey_password }}"
  VALKEY_URI: "valkey://:{{ .Values.secrets.hie_api.valkey_password }}@valkey-service:6379"
  Hie__Transponder__RabbitMq__ConnectionUri: "amqp://guest:{{ .Values.secrets.hie_api.rabbitmq_password }}@rabbitmq-service:5672"
  Hie__DistributedCache__Valkey__ConnectionString: "valkey-service:6379,password={{ .Values.secrets.hie_api.valkey_password }}"
type: "Opaque"
