---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "smartconnect-api-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "smartconnect-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.smartconnect_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.smartconnect_api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.smartconnect_api.port_http | int | toString }}"
  SMARTCONNECT_HOST: "{{ .Values.config.smartconnect_api.SMARTCONNECT_HOST }}"
  SMARTCONNECT_PORT: "{{ .Values.config.smartconnect_api.SMARTCONNECT_PORT }}"
  SMARTCONNECT_USERNAME: "{{ .Values.config.smartconnect_api.SMARTCONNECT_USERNAME }}"
  SMARTCONNECT_JDBCCONNECTIONSTRING: "{{ .Values.config.smartconnect_api.SMARTCONNECT_JDBCCONNECTIONSTRING }}"
  SMARTCONNECT_DATABASENAME: "{{ .Values.config.smartconnect_api.SMARTCONNECT_DATABASENAME }}"
  HANGFIRE_HOST: "{{ .Values.config.smartconnect_api.HANGFIRE_HOST }}"
  HANGFIRE_PORT: "{{ .Values.config.smartconnect_api.HANGFIRE_PORT }}"
  HANGFIRE_USERNAME: "{{ .Values.config.smartconnect_api.HANGFIRE_USERNAME }}"
  HANGFIRE_JDBCCONNECTIONSTRING: "{{ .Values.config.smartconnect_api.HANGFIRE_JDBCCONNECTIONSTRING }}"
  HANGFIRE_DATABASENAME: "{{ .Values.config.smartconnect_api.HANGFIRE_DATABASENAME }}"
  RABBITMQ_HOST: "{{ .Values.config.smartconnect_api.RABBITMQ_HOST }}"
  RABBITMQ_PORT: "{{ .Values.config.smartconnect_api.RABBITMQ_PORT }}"
  RABBITMQ_USERNAME: "{{ .Values.config.smartconnect_api.RABBITMQ_USERNAME }}"
  VALKEY_HOST: "{{ .Values.config.smartconnect_api.VALKEY_HOST }}"
  VALKEY_PORT: "{{ .Values.config.smartconnect_api.VALKEY_PORT }}"
  SmartConnect__Transponder__EnableOutboxRelay: "{{ .Values.config.smartconnect_api.SmartConnect__Transponder__EnableOutboxRelay }}"
  SmartConnect__Authentication__Authority: "{{ .Values.config.smartconnect_api.SmartConnect__Authentication__Authority }}"
  SmartConnect__Authentication__Audience: "{{ .Values.config.smartconnect_api.SmartConnect__Authentication__Audience }}"
  SmartConnect__SourceConnectors__0__Name: "{{ .Values.config.smartconnect_api.SmartConnect__SourceConnectors__0__Name }}"
  SmartConnect__SourceConnectors__0__Kind: "{{ .Values.config.smartconnect_api.SmartConnect__SourceConnectors__0__Kind }}"
  SmartConnect__SourceConnectors__0__DefaultFlowId: "{{ .Values.config.smartconnect_api.SmartConnect__SourceConnectors__0__DefaultFlowId }}"
  SmartConnect__SourceConnectors__0__Parameters__Port: "{{ .Values.config.smartconnect_api.SmartConnect__SourceConnectors__0__Parameters__Port }}"
  SmartConnect__SourceConnectors__1__Name: "{{ .Values.config.smartconnect_api.SmartConnect__SourceConnectors__1__Name }}"
  SmartConnect__SourceConnectors__1__Kind: "{{ .Values.config.smartconnect_api.SmartConnect__SourceConnectors__1__Kind }}"
  SmartConnect__SourceConnectors__1__DefaultFlowId: "{{ .Values.config.smartconnect_api.SmartConnect__SourceConnectors__1__DefaultFlowId }}"
  SmartConnect__SourceConnectors__1__Parameters__Directory: "{{ .Values.config.smartconnect_api.SmartConnect__SourceConnectors__1__Parameters__Directory }}"
  SmartConnect__SourceConnectors__1__Parameters__Pattern: "{{ .Values.config.smartconnect_api.SmartConnect__SourceConnectors__1__Parameters__Pattern }}"
