---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "smartconnect-api-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "smartconnect-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  ConnectionStrings__SmartConnect: "Host=postgres-smartconnect-service;Port=5432;Username=postgres;Password={{ .Values.secrets.smartconnect_api.postgres_smartconnect_password }};Database=dialysis_smartconnect"
  SMARTCONNECT_PASSWORD: "{{ .Values.secrets.smartconnect_api.postgres_smartconnect_password }}"
  SMARTCONNECT_URI: "postgresql://postgres:{{ .Values.secrets.smartconnect_api.postgres_smartconnect_password }}@postgres-smartconnect-service:5432/dialysis_smartconnect"
  ConnectionStrings__Hangfire: "Host=postgres-smartconnect-service;Port=5432;Username=postgres;Password={{ .Values.secrets.smartconnect_api.postgres_smartconnect_password }};Database=dialysis_smartconnect"
  HANGFIRE_PASSWORD: "{{ .Values.secrets.smartconnect_api.postgres_smartconnect_password }}"
  HANGFIRE_URI: "postgresql://postgres:{{ .Values.secrets.smartconnect_api.postgres_smartconnect_password }}@postgres-smartconnect-service:5432/dialysis_smartconnect"
  ConnectionStrings__rabbitmq: "amqp://guest:{{ .Values.secrets.smartconnect_api.rabbitmq_password }}@rabbitmq-service:5672"
  RABBITMQ_PASSWORD: "{{ .Values.secrets.smartconnect_api.rabbitmq_password }}"
  RABBITMQ_URI: "amqp://guest:{{ .Values.secrets.smartconnect_api.rabbitmq_password }}@rabbitmq-service:5672"
  ConnectionStrings__valkey: "valkey-service:6379,password={{ .Values.secrets.smartconnect_api.valkey_password }}"
  VALKEY_PASSWORD: "{{ .Values.secrets.smartconnect_api.valkey_password }}"
  VALKEY_URI: "valkey://:{{ .Values.secrets.smartconnect_api.valkey_password }}@valkey-service:6379"
  SmartConnect__Transponder__RabbitMq__ConnectionUri: "amqp://guest:{{ .Values.secrets.smartconnect_api.rabbitmq_password }}@rabbitmq-service:5672"
  SmartConnect__DistributedCache__Valkey__ConnectionString: "valkey-service:6379,password={{ .Values.secrets.smartconnect_api.valkey_password }}"
type: "Opaque"
