// <auto-generated />
using System;
using Dialysis.PDMS.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dialysis.PDMS.Persistence.Migrations
{
    [DbContext(typeof(PdmsDbContext))]
    [Migration("20260603013022_AddReportTemplateLanguageCode")]
    partial class AddReportTemplateLanguageCode
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("pdms")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dialysis.BuildingBlocks.Fhir.Audit.EntityFrameworkCore.AuditEventRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AgentId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ModuleSlug")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ResourceId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResourceJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Subtype")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("RecordedAt");

                    b.HasIndex("ResourceType", "ResourceId");

                    b.ToTable("audit_events", "fhir_audit");
                });

            modelBuilder.Entity("Dialysis.BuildingBlocks.Fhir.BulkData.EntityFrameworkCore.ExportJobRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeIdentificationProfile")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Error")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("GroupId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("OutputsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RequestorId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResourceTypesCsv")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTimeOffset?>("Since")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("export_jobs", "fhir_export");
                });

            modelBuilder.Entity("Dialysis.BuildingBlocks.Fhir.Subscriptions.EntityFrameworkCore.NotificationOutboxRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("DeliveredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("EnqueuedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "DeliveredAt");

                    b.ToTable("notification_outbox", "fhir_subscriptions");
                });

            modelBuilder.Entity("Dialysis.BuildingBlocks.Fhir.Subscriptions.EntityFrameworkCore.SubscriptionRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ChannelEndpoint")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ChannelHeader")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("ConsecutiveFailures")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FilterParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("LastNotificationAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("TopicUrl")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("TopicUrl", "Status");

                    b.ToTable("subscriptions", "fhir_subscriptions");
                });

            modelBuilder.Entity("Dialysis.BuildingBlocks.Transponder.Persistence.EntityFrameworkCore.TransponderInboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeduplicationKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("RoutingKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("CompletedAtUtc");

                    b.HasIndex("DeduplicationKey")
                        .IsUnique();

                    b.ToTable("InboxMessages", "pdms");
                });

            modelBuilder.Entity("Dialysis.BuildingBlocks.Transponder.Persistence.EntityFrameworkCore.TransponderOutboxMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssemblyQualifiedEventType")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("W3CTraceParent")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAtUtc");

                    b.ToTable("OutboxMessages", "pdms");
                });

            modelBuilder.Entity("Dialysis.BuildingBlocks.Transponder.Persistence.EntityFrameworkCore.TransponderSagaInstanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InstanceKey")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("SagaKind")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("StateJson")
                        .HasColumnType("text");

                    b.Property<string>("StateName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("SagaKind", "InstanceKey")
                        .IsUnique();

                    b.ToTable("SagaInstances", "pdms");
                });

            modelBuilder.Entity("Dialysis.PDMS.Medications.Domain.IvPumpInfusion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ActualRateMlPerHour")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<Guid>("ChairId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InfusedVolumeMl")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<decimal>("ProgrammedRateMlPerHour")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("ProgrammedVolumeMl")
                        .HasPrecision(12, 4)
                        .HasColumnType("numeric(12,4)");

                    b.Property<string>("PumpDeviceId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("VendorCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("ChairId");

                    b.HasIndex("SessionId", "PumpDeviceId", "Status");

                    b.ToTable("IvPumpInfusions", "pdms_medications");
                });

            modelBuilder.Entity("Dialysis.PDMS.Medications.Domain.MedicationAdministrationEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActorSub")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("MarId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("RelatedOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Route")
                        .HasColumnType("integer");

                    b.Property<bool>("WasAdministered")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("MarId");

                    b.HasIndex("OccurredAtUtc");

                    b.ToTable("MedicationAdministrationEntries", "pdms_medications");
                });

            modelBuilder.Entity("Dialysis.PDMS.Medications.Domain.MedicationAdministrationRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("SessionId")
                        .IsUnique();

                    b.ToTable("MedicationAdministrationRecords", "pdms_medications");
                });

            modelBuilder.Entity("Dialysis.PDMS.Medications.Domain.MedicationInventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LotNumber")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("OnHandUnits")
                        .HasColumnType("integer");

                    b.Property<int>("Threshold")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MedicationInventoryItems", "pdms_medications");
                });

            modelBuilder.Entity("Dialysis.PDMS.OnCall.Domain.AlarmDispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcknowledgedBySub")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("AlarmCode")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("ChairId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<int>("CurrentLinkIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<Guid>("InfusionId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RotationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Severity")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("Status");

                    b.HasIndex("ChairId", "StartedAtUtc");

                    b.ToTable("AlarmDispatches", "pdms_oncall");
                });

            modelBuilder.Entity("Dialysis.PDMS.OnCall.Domain.EscalationPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("CriticalBackupWindow")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("CriticalPrimaryWindow")
                        .HasColumnType("interval");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("InformationalPrimaryWindow")
                        .HasColumnType("interval");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("QuietHoursSuppressNonCritical")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<TimeSpan>("WarningBackupWindow")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("WarningPrimaryWindow")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EscalationPolicies", "pdms_oncall");
                });

            modelBuilder.Entity("Dialysis.PDMS.OnCall.Domain.OnCallRotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Backup")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<Guid>("ChairId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateOnly>("EffectiveFromUtc")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveUntilUtc")
                        .HasColumnType("date");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Primary")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Shift")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Supervisor")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ChairId", "EffectiveFromUtc", "EffectiveUntilUtc");

                    b.ToTable("OnCallRotations", "pdms_oncall");
                });

            modelBuilder.Entity("Dialysis.PDMS.Reporting.Domain.ReportTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LanguageCode")
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)");

                    b.Property<int?>("PublishedVersionNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "Kind", "LanguageCode")
                        .IsUnique();

                    b.ToTable("ReportTemplates", "pdms_reporting");
                });

            modelBuilder.Entity("Dialysis.PDMS.Reporting.Domain.SessionReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeliveredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("GeneratedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StorageRef")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("PatientId", "Kind");

                    b.ToTable("SessionReports", "pdms_reporting");
                });

            modelBuilder.Entity("Dialysis.PDMS.TreatmentSessions.Domain.DialysisMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<Guid?>("CurrentSessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime?>("LastSeenUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ModelCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.Property<string>("VendorCode")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("SerialNumber")
                        .IsUnique();

                    b.ToTable("Machines", "pdms_telemetry");
                });

            modelBuilder.Entity("Dialysis.PDMS.TreatmentSessions.Domain.DialysisSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AbortReasonCode")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("AchievedUfVolumeLiters")
                        .HasPrecision(8, 3)
                        .HasColumnType("numeric(8,3)");

                    b.Property<DateTime?>("ActualEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ActualStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("MachineId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ScheduledStartUtc");

                    b.ToTable("DialysisSessions", "pdms_sessions");
                });

            modelBuilder.Entity("Dialysis.PDMS.TreatmentSessions.Domain.IntradialyticReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("ArterialPressureMmHg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<decimal>("ConductivityMsPerCm")
                        .HasPrecision(6, 3)
                        .HasColumnType("numeric(6,3)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<int>("DiastolicBloodPressure")
                        .HasColumnType("integer");

                    b.Property<int>("HeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SystolicBloodPressure")
                        .HasColumnType("integer");

                    b.Property<decimal>("UltrafiltrationRateMlPerHour")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.Property<decimal>("VenousPressureMmHg")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId", "ObservedAtUtc");

                    b.ToTable("IntradialyticReadings", "pdms_sessions");
                });

            modelBuilder.Entity("Dialysis.PDMS.TreatmentSessions.Domain.MdcCodeCatalogEntry", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("bigint");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsVendorSpecific")
                        .HasColumnType("boolean");

                    b.Property<string>("Units")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ObservationCodes", "pdms_telemetry");
                });

            modelBuilder.Entity("Dialysis.PDMS.TreatmentSessions.Domain.RawHl7Message", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<int>("Direction")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageControlId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReceivedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MessageControlId");

                    b.HasIndex("MachineId", "ReceivedAtUtc");

                    b.ToTable("RawHl7Messages", "pdms_telemetry");
                });

            modelBuilder.Entity("Dialysis.PDMS.TreatmentSessions.Domain.TreatmentAlarm", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("AcknowledgedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("AlarmCode")
                        .HasColumnType("bigint");

                    b.Property<string>("AlarmPhase")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("AlarmSource")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("CreatedAt");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DeletedAt");

                    b.Property<string>("DeletedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("DeletedBy");

                    b.Property<DateTime>("FirstObservedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("IsDeleted");

                    b.Property<DateTime>("LastObservedUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("UpdatedAt");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("UpdatedBy");

                    b.HasKey("Id");

                    b.HasIndex("MachineId", "State");

                    b.HasIndex("SessionId", "FirstObservedUtc");

                    b.ToTable("TreatmentAlarms", "pdms_telemetry");
                });

            modelBuilder.Entity("Dialysis.PDMS.TreatmentSessions.Domain.TreatmentObservation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContainmentPath")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MachineId")
                        .HasColumnType("uuid");

                    b.Property<long>("MdcCode")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.PrimitiveCollection<int[]>("ProfileTimesSeconds")
                        .HasColumnType("integer[]");

                    b.PrimitiveCollection<decimal[]>("ProfileValues")
                        .HasColumnType("numeric[]");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SourceMessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("Units")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<decimal?>("ValueNumeric")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)");

                    b.Property<string>("ValueString")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("MdcCode");

                    b.HasIndex("MachineId", "ObservedAtUtc");

                    b.HasIndex("SessionId", "ObservedAtUtc");

                    b.ToTable("TreatmentObservations", "pdms_telemetry");
                });

            modelBuilder.Entity("Dialysis.PDMS.Medications.Domain.IvPumpInfusion", b =>
                {
                    b.OwnsOne("Dialysis.PDMS.Medications.Domain.MedicationCoding", "Medication", b1 =>
                        {
                            b1.Property<Guid>("IvPumpInfusionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("MedicationCode");

                            b1.Property<string>("CodeSystem")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("MedicationCodeSystem");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("MedicationDisplay");

                            b1.HasKey("IvPumpInfusionId");

                            b1.ToTable("IvPumpInfusions", "pdms_medications");

                            b1.WithOwner()
                                .HasForeignKey("IvPumpInfusionId");
                        });

                    b.Navigation("Medication");
                });

            modelBuilder.Entity("Dialysis.PDMS.Medications.Domain.MedicationAdministrationEntry", b =>
                {
                    b.HasOne("Dialysis.PDMS.Medications.Domain.MedicationAdministrationRecord", null)
                        .WithMany("Entries")
                        .HasForeignKey("MarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Dialysis.PDMS.Medications.Domain.Dose", "Dose", b1 =>
                        {
                            b1.Property<Guid>("MedicationAdministrationEntryId")
                                .HasColumnType("uuid");

                            b1.Property<decimal>("Quantity")
                                .HasPrecision(12, 4)
                                .HasColumnType("numeric(12,4)")
                                .HasColumnName("DoseQuantity");

                            b1.Property<string>("Unit")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)")
                                .HasColumnName("DoseUnit");

                            b1.HasKey("MedicationAdministrationEntryId");

                            b1.ToTable("MedicationAdministrationEntries", "pdms_medications");

                            b1.WithOwner()
                                .HasForeignKey("MedicationAdministrationEntryId");
                        });

                    b.OwnsOne("Dialysis.PDMS.Medications.Domain.MedicationCoding", "Medication", b1 =>
                        {
                            b1.Property<Guid>("MedicationAdministrationEntryId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("MedicationCode");

                            b1.Property<string>("CodeSystem")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("MedicationCodeSystem");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("MedicationDisplay");

                            b1.HasKey("MedicationAdministrationEntryId");

                            b1.ToTable("MedicationAdministrationEntries", "pdms_medications");

                            b1.WithOwner()
                                .HasForeignKey("MedicationAdministrationEntryId");
                        });

                    b.Navigation("Dose")
                        .IsRequired();

                    b.Navigation("Medication")
                        .IsRequired();
                });

            modelBuilder.Entity("Dialysis.PDMS.Medications.Domain.MedicationInventoryItem", b =>
                {
                    b.OwnsOne("Dialysis.PDMS.Medications.Domain.MedicationCoding", "Medication", b1 =>
                        {
                            b1.Property<Guid>("MedicationInventoryItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("MedicationCode");

                            b1.Property<string>("CodeSystem")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("MedicationCodeSystem");

                            b1.Property<string>("DisplayName")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)")
                                .HasColumnName("MedicationDisplay");

                            b1.HasKey("MedicationInventoryItemId");

                            b1.HasIndex("CodeSystem", "Code");

                            b1.ToTable("MedicationInventoryItems", "pdms_medications");

                            b1.WithOwner()
                                .HasForeignKey("MedicationInventoryItemId");
                        });

                    b.Navigation("Medication")
                        .IsRequired();
                });

            modelBuilder.Entity("Dialysis.PDMS.OnCall.Domain.AlarmDispatch", b =>
                {
                    b.OwnsMany("Dialysis.PDMS.OnCall.Domain.AlarmDispatchAttempt", "Attempts", b1 =>
                        {
                            b1.Property<Guid>("AlarmDispatchId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Sequence")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Sequence"));

                            b1.Property<string>("Address")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<DateTime>("AttemptedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<int>("ChainLinkIndex")
                                .HasColumnType("integer");

                            b1.Property<int>("Channel")
                                .HasColumnType("integer");

                            b1.Property<bool>("Delivered")
                                .HasColumnType("boolean");

                            b1.Property<string>("FailureReason")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)");

                            b1.HasKey("AlarmDispatchId", "Sequence");

                            b1.ToTable("AlarmDispatchAttempts", "pdms_oncall");

                            b1.WithOwner()
                                .HasForeignKey("AlarmDispatchId");
                        });

                    b.Navigation("Attempts");
                });

            modelBuilder.Entity("Dialysis.PDMS.Reporting.Domain.ReportTemplate", b =>
                {
                    b.OwnsMany("Dialysis.PDMS.Reporting.Domain.ReportTemplateVersion", "Versions", b1 =>
                        {
                            b1.Property<Guid>("TemplateId")
                                .HasColumnType("uuid");

                            b1.Property<int>("VersionNumber")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("VersionNumber"));

                            b1.Property<DateTime>("AuthoredAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("AuthoredBySub")
                                .IsRequired()
                                .HasMaxLength(256)
                                .HasColumnType("character varying(256)");

                            b1.Property<string>("BodyMarkdown")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("TemplateId", "VersionNumber");

                            b1.ToTable("ReportTemplateVersions", "pdms_reporting");

                            b1.WithOwner()
                                .HasForeignKey("TemplateId");
                        });

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Dialysis.PDMS.TreatmentSessions.Domain.DialysisSession", b =>
                {
                    b.OwnsOne("Dialysis.PDMS.TreatmentSessions.Domain.SessionPrescription", "Prescription", b1 =>
                        {
                            b1.Property<Guid>("DialysisSessionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("AnticoagulationProtocolCode")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("AnticoagulationProtocolCode");

                            b1.Property<int>("BloodFlowRateMlPerMin")
                                .HasColumnType("integer")
                                .HasColumnName("BloodFlowRateMlPerMin");

                            b1.Property<decimal>("DialysateCalciumMmolPerL")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("DialysateCalciumMmolPerL");

                            b1.Property<int>("DialysateFlowRateMlPerMin")
                                .HasColumnType("integer")
                                .HasColumnName("DialysateFlowRateMlPerMin");

                            b1.Property<decimal>("DialysatePotassiumMmolPerL")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("DialysatePotassiumMmolPerL");

                            b1.Property<decimal>("DialysateSodiumMmolPerL")
                                .HasPrecision(5, 2)
                                .HasColumnType("numeric(5,2)")
                                .HasColumnName("DialysateSodiumMmolPerL");

                            b1.Property<string>("DialyzerModel")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)")
                                .HasColumnName("DialyzerModel");

                            b1.Property<int>("PrescribedDurationMinutes")
                                .HasColumnType("integer")
                                .HasColumnName("PrescribedDurationMinutes");

                            b1.Property<decimal>("TargetUfVolumeLiters")
                                .HasPrecision(8, 3)
                                .HasColumnType("numeric(8,3)")
                                .HasColumnName("TargetUfVolumeLiters");

                            b1.HasKey("DialysisSessionId");

                            b1.ToTable("DialysisSessions", "pdms_sessions");

                            b1.WithOwner()
                                .HasForeignKey("DialysisSessionId");
                        });

                    b.OwnsOne("Dialysis.PDMS.TreatmentSessions.Domain.VascularAccess", "Access", b1 =>
                        {
                            b1.Property<Guid>("DialysisSessionId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly>("EstablishedOn")
                                .HasColumnType("date")
                                .HasColumnName("AccessEstablishedOn");

                            b1.Property<int>("Kind")
                                .HasColumnType("integer")
                                .HasColumnName("AccessKind");

                            b1.Property<string>("Site")
                                .IsRequired()
                                .HasMaxLength(128)
                                .HasColumnType("character varying(128)")
                                .HasColumnName("AccessSite");

                            b1.HasKey("DialysisSessionId");

                            b1.ToTable("DialysisSessions", "pdms_sessions");

                            b1.WithOwner()
                                .HasForeignKey("DialysisSessionId");
                        });

                    b.Navigation("Access")
                        .IsRequired();

                    b.Navigation("Prescription")
                        .IsRequired();
                });

            modelBuilder.Entity("Dialysis.PDMS.TreatmentSessions.Domain.IntradialyticReading", b =>
                {
                    b.HasOne("Dialysis.PDMS.TreatmentSessions.Domain.DialysisSession", null)
                        .WithMany("Readings")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dialysis.PDMS.Medications.Domain.MedicationAdministrationRecord", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("Dialysis.PDMS.TreatmentSessions.Domain.DialysisSession", b =>
                {
                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
