parameters:
  lab_api:
    port_http: 8080
    lab_api_image: "lab-api:latest"
secrets:
  postgres_lab:
    postgres_lab_password: ""
  lab_api:
    ConnectionStrings__Lab: ""
    postgres_lab_password: ""
    LAB_URI: ""
    ConnectionStrings__Hangfire: ""
    HANGFIRE_URI: ""
config:
  postgres_lab:
    POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
    POSTGRES_USER: "postgres"
  lab_api:
    OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "in_memory"
    ASPNETCORE_FORWARDEDHEADERS_ENABLED: "true"
    HTTP_PORTS: ""
    LAB_HOST: "postgres-lab-service"
    LAB_PORT: "5432"
    LAB_USERNAME: "postgres"
    LAB_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-lab-service:5432/dialysis_lab"
    LAB_DATABASENAME: "dialysis_lab"
    HANGFIRE_HOST: "postgres-lab-service"
    HANGFIRE_PORT: "5432"
    HANGFIRE_USERNAME: "postgres"
    HANGFIRE_JDBCCONNECTIONSTRING: "jdbc:postgresql://postgres-lab-service:5432/dialysis_lab"
    HANGFIRE_DATABASENAME: "dialysis_lab"
    rabbitmq_connection: "amqp://guest:CHANGE-ME@rabbitmq-service:5672"
    valkey_connection: "valkey-service:6379,password=CHANGE-ME"
    Lab__Transponder__EnableOutboxRelay: "true"
    keycloak_authority: "http://keycloak-service:8081/realms/dialysis"
    Lab__Authentication__Audience: "account"
