// <auto-generated />
using System;
using Dialysis.Treatment.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dialysis.Treatment.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TreatmentDbContext))]
    [Migration("20260218201613_AddTimeSeriesObservationIndex")]
    partial class AddTimeSeriesObservationIndex
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dialysis.Treatment.Application.Domain.Observation", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipmentInstanceId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provenance")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceRange")
                        .HasColumnType("text");

                    b.Property<string>("ResultStatus")
                        .HasColumnType("text");

                    b.Property<string>("SubId")
                        .HasColumnType("text");

                    b.Property<string>("TreatmentSessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentSessionId");

                    b.HasIndex("TreatmentSessionId", "Level");

                    b.HasIndex("TreatmentSessionId", "ObservedAtUtc")
                        .HasDatabaseName("IX_Observations_SessionId_ObservedAtUtc");

                    b.HasIndex("TreatmentSessionId", "Code", "SubId");

                    b.ToTable("Observations", (string)null);
                });

            modelBuilder.Entity("Dialysis.Treatment.Application.Domain.TreatmentSession", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Modality")
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .HasColumnType("text");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("integer");

                    b.Property<string>("PatientMrn")
                        .HasColumnType("text");

                    b.Property<string>("Phase")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("default");

                    b.Property<int?>("TherapyTimePrescribedMin")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("PatientMrn");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId", "SessionId")
                        .IsUnique();

                    b.ToTable("TreatmentSessions", (string)null);
                });

            modelBuilder.Entity("Dialysis.Treatment.Application.Domain.Observation", b =>
                {
                    b.HasOne("Dialysis.Treatment.Application.Domain.TreatmentSession", null)
                        .WithMany("Observations")
                        .HasForeignKey("TreatmentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dialysis.Treatment.Application.Domain.TreatmentSession", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
