// <auto-generated />
using System;
using Dialysis.Treatment.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dialysis.Treatment.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TreatmentDbContext))]
    partial class TreatmentDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dialysis.Treatment.Application.Domain.Observation", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("EffectiveTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EquipmentInstanceId")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Level")
                        .HasColumnType("text");

                    b.Property<double?>("MessageTimeDriftSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("ObservedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Provenance")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceRange")
                        .HasColumnType("text");

                    b.Property<string>("ResultStatus")
                        .HasColumnType("text");

                    b.Property<string>("SubId")
                        .HasColumnType("text");

                    b.Property<string>("TreatmentSessionId")
                        .IsRequired()
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TreatmentSessionId");

                    b.HasIndex("TreatmentSessionId", "Level");

                    b.HasIndex("TreatmentSessionId", "ObservedAtUtc")
                        .HasDatabaseName("IX_Observations_SessionId_ObservedAtUtc");

                    b.HasIndex("TreatmentSessionId", "Code", "SubId");

                    b.ToTable("Observations", (string)null);
                });

            modelBuilder.Entity("Dialysis.Treatment.Application.Domain.TreatmentSession", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceEui64")
                        .HasColumnType("text");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Modality")
                        .HasColumnType("text");

                    b.Property<string>("Mode")
                        .HasColumnType("text");

                    b.Property<int>("ObservationCount")
                        .HasColumnType("integer");

                    b.Property<string>("PatientMrn")
                        .HasColumnType("text");

                    b.Property<string>("Phase")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("default");

                    b.Property<string>("TherapyId")
                        .HasColumnType("text");

                    b.Property<int?>("TherapyTimePrescribedMin")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("PatientMrn");

                    b.HasIndex("Status");

                    b.HasIndex("TenantId", "SessionId")
                        .IsUnique();

                    b.HasIndex("TenantId", "StartedAt")
                        .HasDatabaseName("IX_TreatmentSessions_TenantId_StartedAt");

                    b.ToTable("TreatmentSessions", (string)null);
                });

            modelBuilder.Entity("Transponder.Persistence.EntityFramework.InboxStateRecord", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<string>("ConsumerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ProcessedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId", "ConsumerId");

                    b.ToTable("InboxStates", (string)null);
                });

            modelBuilder.Entity("Transponder.Persistence.EntityFramework.OutboxMessageRecord", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(2048)
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EnqueuedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb");

                    b.Property<string>("MessageType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(2048)
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Transponder.Persistence.EntityFramework.SagaStateRecord", b =>
                {
                    b.Property<string>("CorrelationId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<string>("StateType")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<string>("StateData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("CorrelationId", "StateType");

                    b.HasIndex("ConversationId");

                    b.ToTable("SagaStates", (string)null);
                });

            modelBuilder.Entity("Transponder.Persistence.EntityFramework.ScheduledMessageRecord", b =>
                {
                    b.Property<string>("TokenId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DispatchedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TokenId");

                    b.HasIndex("ScheduledTime", "DispatchedTime");

                    b.ToTable("ScheduledMessages", (string)null);
                });

            modelBuilder.Entity("Dialysis.Treatment.Application.Domain.Observation", b =>
                {
                    b.HasOne("Dialysis.Treatment.Application.Domain.TreatmentSession", null)
                        .WithMany("Observations")
                        .HasForeignKey("TreatmentSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Dialysis.Treatment.Application.Domain.TreatmentSession", b =>
                {
                    b.Navigation("Observations");
                });
#pragma warning restore 612, 618
        }
    }
}
