---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "valkey-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "valkey"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  VALKEY_PASSWORD: "{{ .Values.secrets.valkey.valkey_password }}"
type: "Opaque"
