---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "identity-bff-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "identity-bff"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  Identity__Keycloak__ClientSecret: "{{ .Values.secrets.identity_bff.identity_bff_client_secret }}"
type: "Opaque"
