---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "his-bff-deployment"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "his-bff"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Chart.Name }}"
        app.kubernetes.io/component: "his-bff"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - image: "{{ .Values.parameters.his_bff.his_bff_image }}"
          name: "his-bff"
          envFrom:
            - configMapRef:
                name: "his-bff-config"
            - secretRef:
                name: "his-bff-secrets"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: 5301
          resources:
            limits:
              cpu: "250m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "128Mi"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Chart.Name }}"
      app.kubernetes.io/component: "his-bff"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
