---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "smartconnect-api-deployment"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "smartconnect-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "{{ .Chart.Name }}"
        app.kubernetes.io/component: "smartconnect-api"
        app.kubernetes.io/instance: "{{ .Release.Name }}"
    spec:
      containers:
        - image: "{{ .Values.parameters.smartconnect_api.smartconnect_api_image }}"
          name: "smartconnect-api"
          envFrom:
            - configMapRef:
                name: "smartconnect-api-config"
            - secretRef:
                name: "smartconnect-api-secrets"
          ports:
            - name: "http"
              protocol: "TCP"
              containerPort: {{ .Values.parameters.smartconnect_api.port_http | int }}
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "100m"
              memory: "256Mi"
          imagePullPolicy: "IfNotPresent"
  selector:
    matchLabels:
      app.kubernetes.io/name: "{{ .Chart.Name }}"
      app.kubernetes.io/component: "smartconnect-api"
      app.kubernetes.io/instance: "{{ .Release.Name }}"
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: "RollingUpdate"
