---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "postgres-smartconnect-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "postgres-smartconnect"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  POSTGRES_PASSWORD: "{{ .Values.secrets.postgres_smartconnect.postgres_smartconnect_password }}"
type: "Opaque"
