---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "ehr-bff-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "ehr-bff"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  Bff__Keycloak__ClientSecret: "{{ .Values.secrets.ehr_bff.ehr_bff_client_secret }}"
  ConnectionStrings__Hangfire: "Host=postgres-ehr-service;Port=5432;Username=postgres;Password={{ .Values.secrets.ehr_bff.postgres_ehr_password }};Database=dialysis_ehr"
  HANGFIRE_PASSWORD: "{{ .Values.secrets.ehr_bff.postgres_ehr_password }}"
  HANGFIRE_URI: "postgresql://postgres:{{ .Values.secrets.ehr_bff.postgres_ehr_password }}@postgres-ehr-service:5432/dialysis_ehr"
type: "Opaque"
