// <auto-generated />
using System;
using Dialysis.Alarm.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Dialysis.Alarm.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AlarmDbContext))]
    [Migration("20260221015811_ReplaceIntegrationEventOutboxWithTransponderOutbox")]
    partial class ReplaceIntegrationEventOutboxWithTransponderOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Dialysis.Alarm.Application.Domain.Alarm", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<string>("Abnormality")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.Property<string>("ActivityState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlarmState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("AlarmType")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text");

                    b.Property<string>("EventPhase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InterpretationType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<double?>("MessageTimeDriftSeconds")
                        .HasColumnType("double precision");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Priority")
                        .HasColumnType("text");

                    b.Property<string>("SessionId")
                        .HasColumnType("text");

                    b.Property<string>("SourceCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SourceLimits")
                        .HasColumnType("text");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("default");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("TenantId", "DeviceId");

                    b.HasIndex("TenantId", "SessionId");

                    b.ToTable("Alarms", (string)null);
                });

            modelBuilder.Entity("Dialysis.Alarm.Application.Domain.EscalationIncident", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<int>("ActiveAlarmCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("SessionId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("default");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "OccurredAt");

                    b.ToTable("EscalationIncidents", (string)null);
                });

            modelBuilder.Entity("Transponder.Persistence.EntityFramework.InboxStateRecord", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<string>("ConsumerId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset?>("ProcessedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ReceivedTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MessageId", "ConsumerId");

                    b.ToTable("InboxStates", (string)null);
                });

            modelBuilder.Entity("Transponder.Persistence.EntityFramework.OutboxMessageRecord", b =>
                {
                    b.Property<string>("MessageId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(2048)
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EnqueuedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb");

                    b.Property<string>("MessageType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(2048)
                        .HasColumnType("text");

                    b.HasKey("MessageId");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("Transponder.Persistence.EntityFramework.SagaStateRecord", b =>
                {
                    b.Property<string>("CorrelationId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<string>("StateType")
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<string>("StateData")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset>("UpdatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("CorrelationId", "StateType");

                    b.HasIndex("ConversationId");

                    b.ToTable("SagaStates", (string)null);
                });

            modelBuilder.Entity("Transponder.Persistence.EntityFramework.ScheduledMessageRecord", b =>
                {
                    b.Property<string>("TokenId")
                        .HasMaxLength(26)
                        .HasColumnType("character(26)");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("ContentType")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("DispatchedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Headers")
                        .HasColumnType("jsonb");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ScheduledTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TokenId");

                    b.HasIndex("ScheduledTime", "DispatchedTime");

                    b.ToTable("ScheduledMessages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
