---
apiVersion: "v1"
kind: "Secret"
metadata:
  name: "hie-bff-secrets"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "hie-bff"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
stringData:
  Bff__Keycloak__ClientSecret: "{{ .Values.secrets.hie_bff.hie_bff_client_secret }}"
  ConnectionStrings__Hangfire: "Host=postgres-hie-service;Port=5432;Username=postgres;Password={{ .Values.secrets.hie_bff.postgres_hie_password }};Database=dialysis_hie"
  HANGFIRE_PASSWORD: "{{ .Values.secrets.hie_bff.postgres_hie_password }}"
  HANGFIRE_URI: "postgresql://postgres:{{ .Values.secrets.hie_bff.postgres_hie_password }}@postgres-hie-service:5432/dialysis_hie"
type: "Opaque"
