// <auto-generated />
using Dialysis.SmartConnect.Persistence.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Dialysis.SmartConnect.Persistence.EntityFrameworkCore.SqlServer.Migrations;

[DbContext(typeof(SmartConnectDbContext))]
partial class SmartConnectDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.7")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.IntegrationFlowEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<string>("PipelineJson")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("RuntimeState")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.ToTable("IntegrationFlows", "smartconnect");
            });

        modelBuilder.Entity("Dialysis.SmartConnect.Persistence.EntityFrameworkCore.Entities.MessageLedgerEntryEntity", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier");

                b.Property<string>("CorrelationId")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("nvarchar(256)");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("datetimeoffset");

                b.Property<string>("Detail")
                    .HasMaxLength(4000)
                    .HasColumnType("nvarchar(4000)");

                b.Property<Guid>("FlowId")
                    .HasColumnType("uniqueidentifier");

                b.Property<Guid>("IntegrationMessageId")
                    .HasColumnType("uniqueidentifier");

                b.Property<int?>("OutboundRouteOrdinal")
                    .HasColumnType("int");

                b.Property<byte[]>("PayloadSnapshot")
                    .HasColumnType("varbinary(max)");

                b.Property<int>("Status")
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasIndex("FlowId", "CreatedAtUtc");

                b.ToTable("MessageLedgerEntries", "smartconnect");
            });
#pragma warning restore 612, 618
    }
}
