---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "hie-api-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "hie-api"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.hie_api.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.hie_api.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.parameters.hie_api.port_http | int | toString }}"
  HIE_HOST: "{{ .Values.config.hie_api.HIE_HOST }}"
  HIE_PORT: "{{ .Values.config.hie_api.HIE_PORT }}"
  HIE_USERNAME: "{{ .Values.config.hie_api.HIE_USERNAME }}"
  HIE_JDBCCONNECTIONSTRING: "{{ .Values.config.hie_api.HIE_JDBCCONNECTIONSTRING }}"
  HIE_DATABASENAME: "{{ .Values.config.hie_api.HIE_DATABASENAME }}"
  HANGFIRE_HOST: "{{ .Values.config.hie_api.HANGFIRE_HOST }}"
  HANGFIRE_PORT: "{{ .Values.config.hie_api.HANGFIRE_PORT }}"
  HANGFIRE_USERNAME: "{{ .Values.config.hie_api.HANGFIRE_USERNAME }}"
  HANGFIRE_JDBCCONNECTIONSTRING: "{{ .Values.config.hie_api.HANGFIRE_JDBCCONNECTIONSTRING }}"
  HANGFIRE_DATABASENAME: "{{ .Values.config.hie_api.HANGFIRE_DATABASENAME }}"
  ConnectionStrings__rabbitmq: "{{ .Values.config.hie_api.rabbitmq_connection }}"
  ConnectionStrings__valkey: "{{ .Values.config.hie_api.valkey_connection }}"
  Hie__Transponder__EnableOutboxRelay: "{{ .Values.config.hie_api.Hie__Transponder__EnableOutboxRelay }}"
  Hie__Transponder__RabbitMq__ConnectionUri: "{{ .Values.config.hie_api.rabbitmq_connection }}"
  Hie__DistributedCache__Valkey__ConnectionString: "{{ .Values.config.hie_api.valkey_connection }}"
  Hie__Authentication__Authority: "{{ .Values.config.hie_api.keycloak_authority }}"
  Hie__Authentication__Audience: "{{ .Values.config.hie_api.Hie__Authentication__Audience }}"
