---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "gateway-config"
  labels:
    app.kubernetes.io/name: "{{ .Chart.Name }}"
    app.kubernetes.io/component: "gateway"
    app.kubernetes.io/instance: "{{ .Release.Name }}"
data:
  OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY: "{{ .Values.config.gateway.OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY }}"
  ASPNETCORE_FORWARDEDHEADERS_ENABLED: "{{ .Values.config.gateway.ASPNETCORE_FORWARDEDHEADERS_ENABLED }}"
  HTTP_PORTS: "{{ .Values.config.gateway.HTTP_PORTS }}"
  ASPNETCORE_URLS: "{{ .Values.config.gateway.ASPNETCORE_URLS }}"
  Gateway__Authority: "{{ .Values.config.gateway.keycloak_authority }}"
  Gateway__Audience: "{{ .Values.config.gateway.Gateway__Audience }}"
  Gateway__RequireAuthentication: "{{ .Values.config.gateway.Gateway__RequireAuthentication }}"
  ReverseProxy__Clusters__identity__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__identity__Destinations__d1__Address }}"
  ReverseProxy__Clusters__his-bff__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__his_bff__Destinations__d1__Address }}"
  ReverseProxy__Clusters__ehr-bff__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__ehr_bff__Destinations__d1__Address }}"
  ReverseProxy__Clusters__pdms-bff__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__pdms_bff__Destinations__d1__Address }}"
  ReverseProxy__Clusters__smartconnect-bff__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__smartconnect_bff__Destinations__d1__Address }}"
  ReverseProxy__Clusters__hie-bff__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__hie_bff__Destinations__d1__Address }}"
  ReverseProxy__Clusters__admin-bff__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__admin_bff__Destinations__d1__Address }}"
  ReverseProxy__Clusters__portal-bff__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__portal_bff__Destinations__d1__Address }}"
  ReverseProxy__Clusters__his-web__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__his_web__Destinations__d1__Address }}"
  ReverseProxy__Clusters__ehr-web__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__ehr_web__Destinations__d1__Address }}"
  ReverseProxy__Clusters__pdms-web__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__pdms_web__Destinations__d1__Address }}"
  ReverseProxy__Clusters__smartconnect-web__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__smartconnect_web__Destinations__d1__Address }}"
  ReverseProxy__Clusters__hie-web__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__hie_web__Destinations__d1__Address }}"
  ReverseProxy__Clusters__admin-web__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__admin_web__Destinations__d1__Address }}"
  ReverseProxy__Clusters__portal-web__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__portal_web__Destinations__d1__Address }}"
  ReverseProxy__Clusters__keycloak__Destinations__d1__Address: "{{ .Values.config.gateway.ReverseProxy__Clusters__keycloak__Destinations__d1__Address }}"
